#!/usr/bin/env ruby
# encoding: utf-8
require 'rubygems'

environment = ARGV[1]
country = ARGV[2] ? ARGV[2] : 'CN'
feed_type = ARGV[3] ? ARGV[3] : 'topfreeapplications'

dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
Dir.chdir dir

ENV['RAILS_ENV'] = environment ? environment : 'production'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

p "== Begin at #{Time.now}"
ToolLookUp.batch_run(country, feed_type)
p "== End at #{Time.now}"